---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/comments/{id}":
    get:
      summary: show comments for discussion
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        description: Discussion ID
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    text:
                      type: string
                    discussion_id:
                      type: integer
    patch:
      summary: update comment
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        description: Comment ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
    put:
      summary: update comment
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        description: Comment ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
    delete:
      summary: delete comment
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        description: Comment ID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: no content
  "/api/v1/comments":
    post:
      summary: create comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                discussion_id:
                  type: integer
              required:
              - text
              - discussion_id
  "/api/v1/discussions":
    get:
      summary: list discussions
      tags:
      - Discussions
      parameters:
      - name: text
        in: query
        description: Search text
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    topic:
                      type: string
                    description:
                      type: string
  "/api/v1/discussions/{id}":
    get:
      summary: show discussion
      tags:
      - Discussions
      parameters:
      - name: id
        in: path
        description: Discussion ID
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: Comments page
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  topic:
                    type: string
                  description:
                    type: string
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        text:
                          type: string
                        discussion_id:
                          type: integer
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
